### PR TITLE
Bumping Lodash from 4.17.11 --> 4.17.12 to fix vulnerability

### PR DESCRIPTION
**Pull request by manwaring**
Lodash 4.17.11 has a [prototype pollution vulnerability](https://snyk.io/vuln/SNYK-JS-LODASH-450202) which prevents publish-please from successfully passing vulnerability scan of projects, see #91 

this change bumps Lodash from 4.17.11 --> 4.17.12 to get the fix

### CODE REVIEW

**Comment by hdorgeval** [comment]
Hi @manwaring : thanks a lot for your contribution: 👍  Let me finalize your PR before merging

**Comment by hdorgeval** [comment]
@manwaring : now I have to fix all red tests. It may take a while. I do my best to publish a new version today

**Comment by hdorgeval** [comment]
@manwaring : your PR has been published to npm

**Comment by manwaring** [comment]
thanks for your help @hdorgeval!  trying to parse test output was intimidating - seeing what you changed to resolve should help me next time :)

**Pull request merged**
