### PR TITLE
Be able to run publish-please in dry mode

### PR DESCRIPTION
**Pull request by hdorgeval**

### CODE REVIEW

**Comment by hdorgeval** [comment]
Hi @inikulin, just a few words to explain what is going on here.

1) I have decided to treat the dry-run mode as a distinct publishing workflow while leaving the standard publishing workflow untouched. This approach of separating the concerns has led to extract every code common to both workflows as a module. 

2) I have decided to move the `testMode` at the lowest possible level in the production code. The purpose for this was to: 
- make both publishing workflows more testable
- augment code coverage

3) Finally, I have decided to completely remove the testMode parameter. The purpose for this was to:
- remove the --testMode option from the possible CLI options because it could be misused by a contributor or a package consumer.
The testMode parameter have been replaced by: 

```js
process.env.PUBLISH_PLEASE_TEST_MODE= true
```

4) The above decisions had a huge impact on all existing tests. As you could see in the CIs, it looks like all tests are mangled with all console.logs. I found this interesting because you really see how the software works and it's much more easier to detect wrong behaviours.

5) I have also decided to be able to use publish-please dry-run mode inside publish-please project itself(eat our own dog food principle).
- This has lead to modifying some files at the root of the project. Thank's to this I have discovered a "bug" in the existing .publishrc file (prepublishScript instead of prePublishScript)

**Comment by hdorgeval** [comment]
Hi @Xunnamius, @AndreyBelym : could you give me a short review on this PR, you may just look at the [demo](https://github.com/hdorgeval/publish-please/blob/7b32a7492cf7b19b6f7e0105125226e3240e6df1/media/dry-run-demo.gif)

**Comment by hdorgeval** [comment]
Hi @AndreyBelym , would you mind a quick review ? [demo](https://github.com/hdorgeval/publish-please/blob/7b32a7492cf7b19b6f7e0105125226e3240e6df1/media/dry-run-demo.gif)

**Comment by AndreyBelym** [comment]
Yes, I will take a look.

**Comment by AndreyBelym** [comment]
Look good for me too, thar's a great job!

**Pull request merged**
