### PR TITLE
fix package installation on Windows

### PR DESCRIPTION
**Pull request by hdorgeval**
Be able to install publish-please v3 on Windows

### CODE REVIEW

**Comment by hdorgeval** [comment]
Hi @inikulin , could you check the Appveyor webhook is enabled/configured : https://ci.appveyor.com/api/github/webhook?id=6p7fnou9mgblf1en

**Comment by hdorgeval** [comment]
Hi @inikulin, 
I faced a strange issue while setting up some more tests: suddenly I lost all my changes (2 days lost). 

It just arrives when I setup a new test with `process.chdir(__dirname)` (to force the test to execute under cwd = publish-please instead of publish-please/testing-repo). 

I imagine I got this because of the following code inside the test.js file: 
```js
afterEach(() => exec('git reset --hard HEAD').then(exec('git clean -f -d')));
```
Do you confirm this analysis?

**Comment by inikulin** [comment]
@hdorgeval Yes, I believe that's the reason. You've reseted publish-please repo instead of test repo with this command.

**Comment by hdorgeval** [comment]
@inikulin, thanks for your answer. 

I did some changes in the tests in order to be sure there is no side-effect in dev mode. I have still one test to modify that currently modifies the tracked .publishrc file.

After this change, the dev experience should be smooth and safe regarding the pre/post install and the git reset done in integration tests.

Did you have time to look at the Appveyor WebHook configuration? (I have no access to the settings project to do it by myself)

**Comment by inikulin** [comment]
@hdorgeval I've added a web hook for AppVeyor for the repo

**Comment by hdorgeval** [comment]
Hi @inikulin, Thank you for your help on AppVeyor. Would you mind a final review?

It was a hard task to modify the pre/post install hooks in order to be : 

* dev-friendly (`npm install` is working fine after cloning and any time during the dev), 
* git-friendly (only the `post/pre-install.js` scripts are tracked from the lib directory and they are always in sync with the `src` files), 
* build-friendly (rebuilding the project at any time does not break anything), 
* test-friendly (`npm test` does not break anything)
* platform-friendly

**Comment by hdorgeval** [comment]
@inikulin , my npm username is hdorgeval

**Comment by inikulin** [comment]
@hdorgeval I've added you as a maintainer on npm

**Pull request merged**
